### ISSUE TITLE
Feature Request: Ability to Filter by Language

### ISSUE THREAD

**Issue by godismyjudge95** [christophrumpel/larastreamers#106]
Would be awesome if there was a way to set a language preference to only show streams in a certain language.  This way I can easily see which streams I can understand.

Bonuses would be the ability to save that language preference for future reloads and the ability to only add streams in certain languages to my calendar.

**Comment by christophrumpel** [comment]
Kk get it. I know this can be very useful in the future, especially when we have more streams. Currently, I don't want to over-complicate things and keep it simple until we really need it.

But I will keep in mind for the future and thanks for the suggestion.
