### ISSUE TITLE
Feature: check if the live is currently online on Twitch.

### ISSUE THREAD

**Issue by DanielHe4rt** [christophrumpel/larastreamers#11]
I'm checking on the Twitch API looking for the Schedule API, but apparently it still in [beta](https://discuss.dev.twitch.tv/t/would-it-be-possible-to-get-the-scheduled-list-of-events-being-streamed-on-a-channel/25242).

I was wondering if has any possibility to integrate the Twitch Streamers as a Live On/Off flag only. And making the schedule based on some scrapping command for now.

**Comment by christophrumpel** [comment]
Yeah, let's hope they release the new API soon for this.

You mean something like:

- add a twitch streamer to the db
- check every minute if the streamer is live on twitch
- if it is, add an event to the list of streams?

Sounds a bit too hacky for my taste.

**Comment by DanielHe4rt** [comment]
Hmm I was thinking about we hooks or smth like that. Check every minute sounds like a weird idea.

**Comment by christophrumpel** [comment]
Are there Twitch hooks? Let me know if you have an idea how it could work.

**Comment by mohsenbostan** [comment]
Yes, there is a hook for that. You can see the documentation here: 
https://dev.twitch.tv/docs/api/webhooks-reference#topic-stream-changed

**Comment by christophrumpel** [comment]
Thanks, @mohsenbostan. So this is caught through a user id. This means I would need to store a user id and regularly check if this user has any current live streams, correct?

**Comment by mohsenbostan** [comment]
@christophrumpel you're welcome. Yes, you should save the user ID, but you do not have to check it periodically.
when user submits his channel, you should send a request to Twitch Webhook and subscribe the user for the "Stream Changed" event which you cad find it [here](https://dev.twitch.tv/docs/api/webhooks-reference#subscribe-tounsubscribe-from-events) and the link I gave you before.

Two things must be done: first, you need to create a Twitch callback route, second, you need to create a database field for users' status. once you have subscribed the user, Twitch will automatically send a request to your callback URL whenever a user goes live. so you can update his status.

**Comment by christophrumpel** [comment]
ah right, `webhook`, of course, my bad.

Just to be clear, it only tells me when a stream goes online, not about any scheduled streams, right?

Ok, this sounds like a reasonable solution and I will keep it in mind. I still need to define how I want:

* show streams that are live
* deal with Twitch streams, because streamer could stream on both platforms
* refactor some parts to make it work with youtube and twitch

After that, I can move on with Twitch 👍

**Comment by mohsenbostan** [comment]
Unfortunately there is no official documentation for scheduled streams yet.

**Comment by christophrumpel** [comment]
There is now a discussion about Twitch Integration. Let's use that from now on: #128
