### ISSUE TITLE
Using UTC instead of Europe/Vienna as the default time zone

### ISSUE THREAD

**Issue by mohsenbostan** [christophrumpel/larastreamers#12]
Hello, I checked the source code and found that when new streams are added, it changes the schedule time zone to Europe/Vienna.

I believe UTC should be the default time zone, and you can convert that UTC into the users' time zone in the Home page.

I can update the code and submit a pull request if you agree.

**Comment by christophrumpel** [comment]
Hey, what would be the benefits compared to the current solution? Now, we use the browser's timezone to show localized times.

**Comment by mohsenbostan** [comment]
@christophrumpel
As far as I am aware, UTC refers to Coordinated Universal Time. I've had problems dealing with other timezones in some projects because of conversions. The UTC time will be better and easier to convert in users' timezones.

Check out this article too for more information:
https://kylekatarnls.medium.com/always-use-utc-dates-and-times-8a8200ca3164

**Comment by christophrumpel** [comment]
I've heard of it too but didn't want to change as long as I don't see issues. Thanks for the article. Would you do a RP to adapt it?

**Comment by mohsenbostan** [comment]
I will adopt it tomorrow.

**Comment by nuernbergerA** [comment]
A general issue you have without UTC is daylight saving for example (servers don't see daylight :sunglasses: )
