### ISSUE TITLE
RSS feed doesn't show date/time of stream

### ISSUE THREAD

**Issue by prikkprikkprikk** [christophrumpel/larastreamers#125]
The RSS feed is ordered by the time each item is published on the website, which I think is pretty irrelevant.

I would expect either the entry's date/time to be when the stream event is happening, or at least that the date/time/timezone of  the event is included in the entry's description.

**Comment by christophrumpel** [comment]
Hey @prikkprikkprikk, there is already an ongoing discussion about the RSS Feed, could you please check that here: https://github.com/christophrumpel/larastreamers/discussions/127?converting=1 and add your points there? That would help a lot.
