### ISSUE TITLE
Running stream is labeled as "Upcoming"

### ISSUE THREAD

**Issue by BernhardK91** [christophrumpel/larastreamers#149]
Even if the stream is already running it is labeled as "Upcoming". Perhabs if the stream is already running it should be labeled as "Currently" or "Live now".

![image](https://user-images.githubusercontent.com/5526334/147655995-e1d91baa-ec94-44fe-b651-c1112914f3a1.png)

**Comment by christophrumpel** [comment]
Hey, thanks but I think this was an issue only today because it turned out the console commands weren't running on the new server. Just fixed it, still thanks 👍
