### ISSUE TITLE
"No streams found" when selecting a streamer after using pagination

### ISSUE THREAD

**Issue by JonPurvis** [christophrumpel/larastreamers#165]
If you use Pagination on the archive and go to like page 7, then filter by a Streamer (e.g.) Laravel, because there isn't 7 pages worth of Streams to show, you get:

![image](https://user-images.githubusercontent.com/7534029/148462633-3ca0fc20-2ab8-4ab7-8123-06aefbf56162.png)

I think the pagination parameter should be reset each time you filter by a Streamer.

**Comment by christophrumpel** [comment]
That's a good point. Thanks.

**Comment by SamuelNitsche** [comment]
@christophrumpel Do you want to tackle this in your "fixing bugs" stream or are you open for pull requests?

**Comment by christophrumpel** [comment]
Hey @SamuelNitsche, yeah right. But If you want to help out too, you can and I deal with the PR in the stream :-)

**Comment by JonPurvis** [comment]
Thanks for looking into this and fixing @SamuelNitsche @christophrumpel 😄
