### ISSUE TITLE
Can't subscribe to calendar

### ISSUE THREAD

**Issue by rubenvanerk** [christophrumpel/larastreamers#192]
When I try to subscribe to the calendar (https://larastreamers.com/calendar.ics) in Fastmail, I get the following error:
`Hmm, that didn’t work. Please check the URL is correct.`

I reached out to support, and they gave me the following answer:

> 
> It appears there is an invalid character in the description of some of the events in that calendar. Here is an example:
> ```
> BEGIN:VEVENT
>     UID:s0JHF7FIgyQ
>     DTSTAMP:20210602T071448Z
>     SUMMARY:Laravel Basics: Let's build a start up\, Episode 2
>     DESCRIPTION:Laravel Basics: Let's build a start up\, Episode 2\nJustSteveKi
>      ng\nhttps://[www.youtube.com/watch?v=s0JHF7FIgyQ\n---------------\nIn](http://www.youtube.com/watch?v=s0JHF7FIgyQ\n---------------\nIn) this
>      stream I am going back to basics\, Laravel basics.^M\n^M\nJoin me on a journ
>      ey as I build a fictional start up from scratch\, all live on stream. This
>       will be split over several episodes\, and the more time goes on the more
>      complex parts of our application will get.^M\n^M\nLast time we focused mostl
>      y on routes and views\, some Blade components\, nothing too technical. We
>      started building out some Eloquent Models\, and were just about to start w
>      orking on creating Podcasts. This time we are going to pick up where we le
>      ft off\, and start working the server side interactions for creating podca
>      sts\, what happens when we create a podcast - are there any changes we nee
>      d to make to out Models and migrations?^M\n^M\nRepository: https://github.co/
>      m/JustSteveKing/castr
>     URL:https://www.youtube.com/watch?v=s0JHF7FIgyQ
>     DTSTART:20210603T184500Z
>     DTEND:20210603T194500Z
>     END:VEVENT
> ```
> 
> Notice the "^M" character? That means in carriage return in DOS/Windows, but that's invalid in calendar Description, instead it should just be "\n". If you have access to the remote calendar, changing the description to remove those characters should fix the issue. You should then be able to subscribe to it.

**Comment by christophrumpel** [comment]
Interesting, thanks for details @rubenvanerk. I will take a look 👍

**Comment by christophrumpel** [comment]
Are you on a windows computer? Can you download https://larastreamers.com/calendar.ics and show me the full content of it?

**Comment by rubenvanerk** [comment]
I'm generally on Linux but I've opened the file on Windows in Notepad. Looks like this: https://gist.github.com/rubenvanerk/31a847537765d943dcefc59667ccd34d

**Comment by christophrumpel** [comment]
Thanks. It's interesting because I don't see the mentioned `^M` on my machine and also not on your gist in the output. And since we are using `\n` already, I don't know how to fix that. I wonder if that is only an issue with Fastmail?

**Comment by rubenvanerk** [comment]
I can see them in vim on my Linux machine: 
![image](https://user-images.githubusercontent.com/20305359/153622557-e1dd76ff-bfaf-4959-9e68-8ebf09c288bd.png)

You can't see them in the gist because Windows converted them to actual line breaks.

**Comment by christophrumpel** [comment]
Hm I see. Using VIM I found them now too.

Do you have an idea of how to get rid of them? I had no luck so far with suggestions from https://stackoverflow.com/questions/11852476/php-removing-windows-m-character

**Comment by rubenvanerk** [comment]
I only tested this a bit with tinker, but shouldn't this work: https://github.com/christophrumpel/larastreamers/pull/199 ?
