### ISSUE TITLE
Card spacing issue

### ISSUE THREAD

**Issue by mohsenbostan** [christophrumpel/larastreamers#22]
I looked at the website and found that cards were not properly spaced out vertically.
Here's what they look like:

![image](https://user-images.githubusercontent.com/20592417/118467073-b9d87180-b718-11eb-8249-91b72497a129.png)

I can resolve this issue if you prefer.

**Comment by christophrumpel** [comment]
Thanks, I already have that on my list 👍

**Comment by christophrumpel** [comment]
A little bit better now. There will be time for a full design refresh hopefully.
