### ISSUE TITLE
Failing tests when running locally

### ISSUE THREAD

**Issue by JonPurvis** [christophrumpel/larastreamers#252]
The following tests are currently failing when running the test suite locally:

- Tests\Feature\Http\Livewire\SubmitYouTubeLiveStreamTest > it shows a success message with full youtube url too
- Tests\Feature\Http\Livewire\SubmitYouTubeLiveStreamTest > it clears out the form after submission
- Tests\Feature\Http\Livewire\SubmitYouTubeLiveStreamTest > it shows a success message

With the following error: 

> An email must have a "From" or a "Sender" header.

Possibly due to Symfony Mailer being updated? I think we can specify a value in the `phpunit.xml` file for this.

**Comment by christophrumpel** [comment]
Hey, I missed that one. I believe is not up to date anymore. Tested everything locally and it seems to work. Open it up again if still an issue. greets
