### ISSUE TITLE
Conflict in sail and composer lock PHP versions

### ISSUE THREAD

**Issue by dpetrovaliev** [christophrumpel/larastreamers#262]
Hey Cristopher.

There is a conflict in PHP versions in the laravel sail and the composer lock file references.
I assume that your local version of PHP is 8.1.x but the laravel sail environment uses 8.0 and that causes some issues if you try to composer install within the sail environment.

**Comment by christophrumpel** [comment]
Hey, thanks for letting me know. I don't use Sail myself; could you maybe provide a PR with a fix?
