### ISSUE TITLE
bg-green not getting applied

### ISSUE THREAD

**Issue by JonPurvis** [christophrumpel/larastreamers#288]
When you submit a stream, the success message is missing a background colour

<img width="603" alt="Monosnap Larastreamers Archive 2023-05-21 01-27-49" src="https://github.com/christophrumpel/larastreamers/assets/7534029/675d69e5-5745-4258-9f16-f9c5a98b7123">

`bg-green` should be getting applied

Possibly related to [this commit](https://github.com/christophrumpel/larastreamers/commit/8ff8052c5e843ea7b2d7639b1aa7708b5dd4d7a6) @christophrumpel?

**Comment by christophrumpel** [comment]
Hey, thanks for the hint. I already tried to fix it, but seems that did not work. Now I did it again and it should be fixed 👍

**Comment by JonPurvis** [comment]
Excellent, thanks @christophrumpel 🥳
