### ISSUE TITLE
Improve live stream status checking

### ISSUE THREAD

**Issue by mohsenbostan** [christophrumpel/larastreamers#32]
Hi.
Recently, a new feature was added for checking live stream's status, but I think it is expensive. There is a more efficient way to implement this feature.

Rather than querying all data in the database, query for the saved streams with STATUS_UPCOMING flag which scheduled for the current time or the time that has already passed. Then, if any data was available, send the request to the YouTube API.

In addition, the cron job frequency will need to be altered to every 10 seconds or any other time that is less than 2 minute.

**Comment by christophrumpel** [comment]
Thanks, @mohsenbostan. There are indeed better ways. @nuernbergerA already working on a similar solution to your approach.
