### ISSUE TITLE
Social cards

### ISSUE THREAD

**Issue by nebarg** [christophrumpel/larastreamers#37]
Create a social card for direct links to a stream listed on the site, like:

![image](https://user-images.githubusercontent.com/46636653/118734871-35304500-b837-11eb-8fa7-d687f54cf204.jpeg)

Instead of the add calendar text that obviously can't be clicked on Twitter, maybe have 2 or 3 time zones listed instead.

_thanks to @devgummibeer for the image ~~stolen~~ borrowed from Twitter_

**Comment by christophrumpel** [comment]
Hey, currently the link (just merged that) and the image can be clicked to get to the stream. What else would you like to see? What do you mean by social card?

What other time zones would you want to see? I would assume most people are fine with their local time zone. I might think about a switcher, but more if really needed.

**Comment by nebarg** [comment]
When you post a link to a website on Twitter it tries to pull an image to create a pretty link, ie:

![image](https://user-images.githubusercontent.com/46636653/118855169-68251800-b8cd-11eb-96e5-073bd68c16cd.jpeg)

[twitter cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards)

It would be nice to dynamically create a card for each stream that has the title, and time - I suggested having 2 or 3 times visible just because you obviously can't tailor twitter posts to each persons' timezone so you could show an American timezone, and maybe a UTC one. Perhaps it's not required, just an idea!

**Comment by christophrumpel** [comment]
Ah right, kk now I get it 👍

I think it could be useful, having the same "brand" for all the preview images and also seeing the time in different time zones. But how would that be possible? The default preview image is being created from the link (YouTube video which have no control of). The only way I can think of is to use an image in the tweet and add a URL. The downside I see with this is that you cannot link the image with this approach.

**Comment by nebarg** [comment]
I think the link would have to point to Larastreamers so you could include the meta info/image link that's required, the page could then redirect to YouTube? I'm not sure how the Twitter link preview would handle a page with a redirect, and that's potentially ugly?  I've had a crazy idea that the page linked to from Twitter has some stats on, such as how many times the streamer has streamed, how recently, and potentially tie in with the archive ability (show a list of most recent streams/links).

A button to view stream which then directs to YT would be easier then.

It would also allow you to see some stats on how many times any particular streamer's stream links had been clicked on twitter etc.

**Comment by christophrumpel** [comment]
Ok get it. The idea has some benefits but for now, I think it's too "complex" compared to what it provides. Especially, because I'm fine the YouTube previews too. I'll keep the idea in my mind and maybe later in time we can talk about it again. Still thanks for the idea.
