### ISSUE TITLE
Allow streams of non-english speaking streamers

### ISSUE THREAD

**Issue by felixdorn** [christophrumpel/larastreamers#41]
There is definitely a place for non-english streams even though  i believe most of the streams will be in english. For example, @Caneco on Twitter streamed in Portuguese a while ago, see [this tweet](https://twitter.com/Caneco/status/1390936896323432448) for reference.

Now, assuming we agree that this feature has it's place in the app, here are some possible implementations.

First, add a Language select next to the Livestream ID input which would default to English as Youtube does not expose the Livestream language directly.

A  `lang` column should be added to the `Stream` which would default to `en`.

## Design

**Of course, these two are very ugly but let's focus on how it works rather than how it looks.**

![Tabs on top of the title tomorrow](https://user-images.githubusercontent.com/55788595/118833440-f6d76c00-b8b0-11eb-8710-270f95d67741.png)

Even though it is fairly unlikely to happen, one big con is that if there is a lot of scheduled livestreams with a lot of different languages, it will be very cluncky and not usable at all.

Another design idea similar to what the first implementation of the timezone select was :

![A select to choose the language at the right side of the title tomorrow](https://user-images.githubusercontent.com/55788595/118834647-e2e03a00-b8b1-11eb-8c9a-da2612c71aff.png)
 Here the default selected language could be the one provided in the `Accept-Language` header.

 Livewire  could be used to implement this fairly easily for both propositions.

**Comment by christophrumpel** [comment]
Thanks, @felixdorn for pushing this topic and the first ideas. I wanna start with how many people we know that stream in different languages about Laravel. I'd assume it is currently maybe 5-10 at max. (I might be wrong)

For me, this would mean, that currently there wouldn't be too many streams in different languages so I wouldn't want to start with a "complex" solution like "lang switch".

I think a simple solution would do it too for now. Here is what I suggest:

* add lang field to streams table, default "en" (like you suggested)
* add a lang dropdown (default "en") to the dashboard where I import single streams
* show some kind of country flag for streams in a different lang on the homepage list, or show lang name for every stream. (maybe @Larsklopstra can work on the design again to make it pretty)

What do you think?

**Comment by felixdorn** [comment]
Yeah! It sounds good to me, no need to make it complicated for no reason! I can submit a PR if you want and then @Larsklopstra can make it prettier as you suggested.

**Comment by christophrumpel** [comment]
Cool, yes, please.
