### ISSUE TITLE
(Idea/discussion) Dockerfiles

### ISSUE THREAD

**Issue by beganovich** [christophrumpel/larastreamers#47]
Hey everyone,

I wanted to do some development on the project, but I don't have php80 locally installed. This led me to the idea to PR the docker-compose with all required tools to work on the project.

What are your thoughts on this? 

Thanks.

**Comment by christophrumpel** [comment]
Hey, thanks, Benjamin. Like mentioned, I wouldn't need it myself, but if others are interested too we can think about adding it.

**Comment by christophrumpel** [comment]
Hey @beganovich, I think currently there is not much need for this and since I mostly work on the project I don't want to add code related to different dev environments. We can of course reopen this issue at a later point and integrate it later if needed. Still thanks for your proposal.
