### ISSUE TITLE
Ended streams don't get updated if they are private

### ISSUE THREAD

**Issue by SamuelNitsche** [christophrumpel/larastreamers#50]
I noticed that the live stream of Freek is still displayed as "live" a few hours after the stream has ended. I think this may has something to do with the fact that the vod is private so the current state of the live stream cannot be fetched. 

![image](https://user-images.githubusercontent.com/24483576/120709815-a0c41480-c4bd-11eb-8274-b1f8282af5f5.png)

**Comment by christophrumpel** [comment]
Hey @SamuelNitsche, thanks for the update. I didn't notice the video was private. Need to give this a close looks, thanks

**Comment by SamuelNitsche** [comment]
Same thing happens when the videos get removed.
![grafik](https://user-images.githubusercontent.com/24483576/121179784-644b3c80-c860-11eb-8a38-8ac5f56442ad.png)

I think it would make sense to just remove them from the database as soon as there is no data available. This way removed or private streams are also not visible on the upcoming archive page.
