### ISSUE TITLE
Add search and filter by channel to archive

### ISSUE THREAD

**Issue by christophrumpel** [christophrumpel/larastreamers#53]

**Comment by christophrumpel** [comment]
bonus: language as filter

**Comment by spaantje** [comment]
Hi @christophrumpel 

I want to take a look at this enhancement. But can you explain it a bit more? 

Some questions i have: 
- What do you want to filter on? 
- What do you want to query on with the search (only title, or also body/user/etc)
- Where do you want to position the search on the page. And do you have any idea about the styling?

**Comment by christophrumpel** [comment]
Hey, thanks for working on this issue, I just gave it some thought. I think best would be to:

* have one `search` field (currently only the Archive page because we don't have a long list on upcoming ones)
* it checks `stream.channel_title` and `stream.title`
* I'm not sure about the design yet


I think I need to bring in a designer to help out with a few parts of the app already. Please don't think about the design for now and make it work first with a simple design (search under `Archive` title). Let me know if you need any more details.
