### ISSUE TITLE
Add timezone to calendar.ics

### ISSUE THREAD

**Issue by noplanman** [christophrumpel/larastreamers#55]
As I see it, there is no timezone defined when downloading the `calendar.ics` file, because it implies UTC.

The problem with this, is that when I subscribe to the calendar in my calendar app, it uses my local timezone but takes the time from the ICS file literally, thus having the wrong time.

(Wanted to follow the stream today and was 2 hours late 😅)

Or am I missing something obvious here?

**Comment by noplanman** [comment]
Super strange, there must have been some blip or something.

After forking and setting up the project locally, to see what was happening, the times for the local ICS imports were correct in my app.

Then suddenly the subscribed calendar times all updated and are now correct 🤔

**Comment by christophrumpel** [comment]
Hey @noplanman, that is strange indeed. For me, it always worked and I'm glad it works now for you too. I will keep an eye on that if there happens an issue again 👍
