### ISSUE TITLE
Youtube "short" urls of stream throw an error

### ISSUE THREAD

**Issue by christophrumpel** [christophrumpel/larastreamers#89]
When you currently try to submit a new stream through a `short YT URL` like `https://youtu.be/KSqpABOk1cc`, it throws an error:

`[2021-09-14 11:54:19] production.ERROR: Undefined array key "v"...`

1. We should catch the error
2. Making it work with that URL too would be nice

**Comment by jaetooledev** [comment]
I've just published a fix for this which I hope should do the job!
