### ISSUE TITLE
Feature: Add Newsletter List

### ISSUE THREAD

**Issue by DanielHe4rt** [christophrumpel/larastreamers#9]
The idea is to make a footer with the newsletter field and button.

The table will be pretty simple:

Table: newsletter

id: uuid
email: string
deleted_at: datetime

Routes:

POST - /newsletter
DELETE - /newsletter/{id}

Hope to finish today!

**Comment by DanielHe4rt** [comment]
Also i'm doing it at my live stream!

https://twitch.tv/danielhe4rt

**Comment by christophrumpel** [comment]
Hey, thanks @DanielHe4rt. Nice idea, but I think I would add it differently.

I probably would add the subscribers to my Mailcoach instance and not store them in the db. This way I'm more flexible in sending newsletters through my given system.

**Comment by DanielHe4rt** [comment]
Done!

https://github.com/christophrumpel/larastreamers/pull/10

**Comment by christophrumpel** [comment]
Thanks, #10 is merge but only the footer without the form. I first need to check how I want to send notifications. Because we have Youtube notifications already, then we add calendar events that you can add to your calendar. Currently not sure if I want emails too.
